language: php
dist: focal
php:
  - '7.4'

# Git branches
branches:
  only:
    - master

before_script:
  - composer install

script: php bin/phpunit

after_success:
  - git remote remove origin
  - git remote add origin ssh://qywl6544@qywl6544.odns.fr/home/qywl6544/deployment-test
  - git push -u origin master