language: php
dist: focal
php:
  - '7.4'

# Git branches
branches:
  only:
    - master

before_script:
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: php bin/phpunit --coverage-clover clover.xml

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT