language: php
dist: focal
php:
  - '7.4'

# Git branches
branches:
  only:
    - master

env:
  - GROUP=functional
  - GROUP=unit

before_script:
  - composer install

script: php bin/phpunit --group=$GROUP