os: linux
dist: focal
language: php
php:
  - '7.4'

# Git branches
branches:
  only:
    - master

install:
  - composer install
  - php bin/phpunit

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: php bin/phpunit --coverage-clover clover.xml

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: "G3e1p7NK4Sar1/I1Tbdz4Uko+JnYYQiVKCAJOn/p42TUQoRD4+MLgHiqnlciNjBmdAjFGRiCQJQuUe0SO4HCSkjPEqK9U7YiPqzpRUpkUwEZjnfRCkM7MnBDt96oKiL6oHoVBIlNhOJnuRchmcLkl+q51/x/B/1gxb5ScorryWAFuzvPI82jYR7SyG8MeJei0HZXmGeLq0i0uL/gzOF8LU6uEC8iA6RRM1ncAC/wUOLxIlKiEMgkrAgkx+doFLUbGfIR5P9N6lhLkWx9Rh3u7StT7ToIEJ9vyo2vRDTkrANn9b4SNs/p+RBHIQfaA/T2Umq+zqCqWPwuN7W6gdtt94NwKx7gVeyLbxRcT9j/E9ou+JDW4JnD2+Qa/3DvfntcMN3YnaKpJag7sjBZFYthI2DGPZzkyFT9ADmWsKYt8ri9PdtgRJMltIMRVnDj0dTrb648+7PGtpyVPKTg75c0aUlXAOs+R8RG0dOou2tmXBwT9iIwNokNJ2rTXkH2hFJqPqHOjrEFNTpS12vOni3Fr0PxTMXNcRJ/MGCW4CN+a2w1Ok3RSFUhc3bbVgnWoXWohp15nk7xSR4cKCnBL6WsIFDFEOa+S/BTWAYSA5iUiaZeb223S2B2jI4mboJkW1W/UK7N2uXD3RFiFHn4/hJVUY+t2Ea4D7cFSdeL+wqlzlQ="